apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - postgres.yaml
  - postgres-secret.yaml
patches:
  - path: api-configmap-hybrid-patch.yaml
  - path: api-deployment-hybrid-patch.yaml
