apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hubk
resources:
  - namespace.yaml
  - api-configmap.yaml
  - web-configmap.yaml
  - secret.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml
